### PR TITLE
feat: prefer "origin" or "upstream" remote if exists

### PR DESCRIPTION
**Pull request by rvagg**

### CODE REVIEW

**Review by hogashi — CHANGES_REQUESTED** [review]
Thank you for a p-r.

This extension should copy feature branch URL when the current branch is a feature branch.  Origin branch URL will be weird (404 or the line number differs) if it is a new file or a changed file.

So I'd like to ask you what your problem is in detail.  I'm glad if you tell me "what was happened" and "what is expected."

**Comment by rvagg** [comment]
I have multiple remotes for many repos; sometimes these are local forks, sometimes they are other people's forks. This extension, as it exists today, just picks the first remote from the list in the order presented to the extension and from my experience so far, this ends up being the wrong fork. However, it's not hard to discover the most likely correct remote from convention: it is typical to name the primary remote that you work with "origin", and sometimes this convention is switched to "upstream" (the `gh` commandline tool uses this convention for example when it forks a remote for you). So this change will sift through the remotes that you have for a repo and if it finds one called "origin", will use that, otherwise "upstream", and then if not that will fall back to just picking the first.

**Review by hogashi — APPROVED** [review]
Oh, I have mistaken "remote" with "branch" somehow... I'm sincery sorry for that and thank you again for your explanation.

>This extension, as it exists today, just picks the first remote from the list in the order presented to the extension and from my experience so far, this ends up being the wrong fork. However, it's not hard to discover the most likely correct remote from convention: it is typical to name the primary remote that you work with "origin", and sometimes this convention is switched to "upstream"

That is indeed.  LGTM!

**Comment by hogashi** [comment]
@rvagg I released v0.3.0 including this change. https://github.com/hogashi/vscode-copy-github-permalink/releases/tag/v0.3.0

And it's published already 🚀  https://marketplace.visualstudio.com/items?itemName=hogashi.vscode-copy-github-permalink

**Pull request merged**
